import { useEffect, useMemo, useState } from 'react';
import { formatINR, IMAGE_PRESETS, AVATAR_PRESETS, DEMO_USERS, INITIAL_PITCHES, SAMPLE_INVESTMENTS } from './data/constants';

export default function App() {
  const [users,setUsers]=useState(()=>JSON.parse(localStorage.getItem('innofund_users')||'null')||DEMO_USERS);
  const [currentUser,setCurrentUser]=useState(()=>JSON.parse(localStorage.getItem('innofund_current_user')||'null')||DEMO_USERS[2]);
  const [pitches,setPitches]=useState(()=>JSON.parse(localStorage.getItem('innofund_pitches')||'null')||INITIAL_PITCHES);
  const [investments,setInvestments]=useState(()=>JSON.parse(localStorage.getItem('innofund_investments')||'null')||SAMPLE_INVESTMENTS);
  const [tab,setTab]=useState('explore'),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[sort,setSort]=useState('newest');
  const [selected,setSelected]=useState(null),[auth,setAuth]=useState(null),[funds,setFunds]=useState(false),[toast,setToast]=useState(null);
  const notify=(message,type='success')=>{setToast({message,type});setTimeout(()=>setToast(null),3500)};
  useEffect(()=>localStorage.setItem('innofund_users',JSON.stringify(users)),[users]);
  useEffect(()=>localStorage.setItem('innofund_current_user',JSON.stringify(currentUser)),[currentUser]);
  useEffect(()=>localStorage.setItem('innofund_pitches',JSON.stringify(pitches)),[pitches]);
  useEffect(()=>localStorage.setItem('innofund_investments',JSON.stringify(investments)),[investments]);

  const categories=useMemo(()=>['All',...new Set(pitches.map(p=>p.category))],[pitches]);
  const visible=useMemo(()=>pitches.filter(p=>(category==='All'||p.category===category)&&((p.title+' '+p.tagline+' '+p.pitcherName+' '+p.category).toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='targetHigh'?b.targetAmount-a.targetAmount:sort==='fundedHigh'?(b.raisedAmount/b.targetAmount)-(a.raisedAmount/a.targetAmount):new Date(b.createdAt)-new Date(a.createdAt)),[pitches,category,search,sort]);
  const signIn=(email,password)=>{const u=users.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u){notify('Invalid email or password.','error');return}setCurrentUser(u);setAuth(null);notify(`Welcome back, ${u.name}!`)};
  const signUp=(e)=>{if(users.some(u=>u.email.toLowerCase()===e.email.toLowerCase()))return notify('An account with this email already exists.','error');const u={id:'u_'+Date.now(),name:e.name,email:e.email,password:e.password,role:e.role,company:e.company||'Independent',bio:e.bio||'InnoFund Platform Member',avatar:e.avatar||AVATAR_PRESETS[0],walletBalance:e.role==='investor'?Number(e.initialWallet||1000000):0};setUsers([...users,u]);setCurrentUser(u);setAuth(null);notify(`Welcome to InnoFund, ${u.name}!`)};
  const invest=(p,slots)=>{if(!currentUser)return setAuth('signin');if(currentUser.role!=='investor')return notify('Switch to an Investor account to invest.','error');const amount=p.minInvestmentPerSlot*slots;if(currentUser.walletBalance<amount){setFunds(true);return notify(`You need ${formatINR(amount)} in your wallet.`,'error')}const u={...currentUser,walletBalance:currentUser.walletBalance-amount};setCurrentUser(u);setUsers(users.map(x=>x.id===u.id?u:x));setPitches(pitches.map(x=>x.id===p.id?{...x,raisedAmount:x.raisedAmount+amount}:x));setInvestments([{id:'inv_'+Date.now(),pitchId:p.id,pitchTitle:p.title,investorId:u.id,investorEmail:u.email,investorName:u.name,amount,slotsCount:slots,date:new Date().toISOString().split('T')[0]},...investments]);setSelected(null);notify(`Invested ${formatINR(amount)} in ${p.title}.`)};
  const addFunds=(n)=>{const u={...currentUser,walletBalance:currentUser.walletBalance+Number(n)};setCurrentUser(u);setUsers(users.map(x=>x.id===u.id?u:x));setFunds(false);notify(`Added ${formatINR(n)} to your wallet.`)};
  const createPitch=(e)=>{if(!currentUser||currentUser.role!=='pitcher')return notify('Sign in as a Pitcher to create a campaign.','error');const target=Number(e.targetAmount),investors=Number(e.expectedInvestors)||1;const p={id:'pitch_'+Date.now(),title:e.title,tagline:e.tagline,category:e.category==='Other'&&e.customCategory?e.customCategory:e.category,pitcherId:currentUser.id,pitcherName:currentUser.name,pitcherEmail:currentUser.email,pitcherAvatar:currentUser.avatar,imageUrl:e.imageUrl||IMAGE_PRESETS[0].url,description:e.description,marketOpportunity:e.marketOpportunity,milestones:e.milestones,demoUrl:e.demoUrl,targetAmount:target,expectedInvestors:investors,minInvestmentPerSlot:Math.round(target/investors),raisedAmount:0,createdAt:new Date().toISOString().split('T')[0],status:'Active'};setPitches([p,...pitches]);setTab('mine');notify('Your pitch is live!')};
  const updateStatus=(id,status)=>setPitches(pitches.map(p=>p.id===id?{...p,status}:p));

  return <div className="min-h-screen bg-slate-950 text-slate-100">
    <header className="glass-nav sticky top-0 z-30"><div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between gap-4"><button onClick={()=>setTab('explore')} className="flex items-center gap-2"><span className="w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-slate-950"><i className="fa-solid fa-rocket"/></span><span className="font-black text-xl gradient-text">InnoFund</span></button><nav className="hidden md:flex gap-1">{[['explore','Explore'],['dashboard','Dashboard'],['about','About'],...(currentUser?.role==='pitcher'?[['create','Post Idea'],['mine','My Pitches']]:[])].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-xl text-xs font-bold ${tab===id?'bg-slate-800 text-emerald-400':'text-slate-400 hover:text-white'}`}>{label}</button>)}</nav><div className="flex items-center gap-2">{currentUser?<><button onClick={()=>setFunds(true)} className="hidden sm:flex items-center gap-2 px-3 py-2 rounded-xl bg-slate-900 border border-emerald-500/30 text-emerald-400 text-xs font-bold"><i className="fa-solid fa-wallet"/>{formatINR(currentUser.walletBalance)}</button><img src={currentUser.avatar} className="w-9 h-9 rounded-full object-cover border-2 border-emerald-500" alt="profile"/><button onClick={()=>{setCurrentUser(null);notify('Signed out.')}} className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-400"><i className="fa-solid fa-power-off"/></button></>:<><button onClick={()=>setAuth('signin')} className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs font-bold">Sign In</button><button onClick={()=>setAuth('signup')} className="px-3 py-2 rounded-xl bg-emerald-500 text-slate-950 text-xs font-bold">Sign Up</button></>}</div></div></header>
    <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
      {tab==='explore'&&<><section className="mb-7"><p className="text-emerald-400 text-xs font-bold uppercase tracking-widest">Fractional micro-fundraising</p><h1 className="text-4xl md:text-5xl font-black mt-2">Back the next <span className="gradient-text">big idea.</span></h1><p className="text-slate-400 mt-3 max-w-2xl">Discover promising startups, inspect their campaigns, and invest in affordable slots.</p></section><div className="glass-card rounded-2xl p-4 mb-6 space-y-4"><div className="flex flex-col md:flex-row gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search pitches, founders, technology..." className="flex-1 px-4 py-3 rounded-xl bg-slate-900 border border-slate-800 outline-none focus:border-emerald-500"/><select value={sort} onChange={e=>setSort(e.target.value)} className="px-4 py-3 rounded-xl bg-slate-900 border border-slate-800"><option value="newest">Newest</option><option value="targetHigh">Highest Goal</option><option value="fundedHigh">Most Funded</option></select></div><div className="flex gap-2 overflow-x-auto">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${category===c?'bg-emerald-500 text-slate-950':'bg-slate-900 text-slate-400 border border-slate-800'}`}>{c}</button>)}</div></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{visible.map(p=><PitchCard key={p.id} p={p} onClick={()=>setSelected(p)}/>)}</div></>}
      {tab==='dashboard'&&<Dashboard currentUser={currentUser} pitches={pitches} investments={investments} onSelect={setSelected} onFunds={()=>setFunds(true)} onAuth={()=>setAuth('signin')}/>} 
      {tab==='about'&&<About/>}
      {tab==='create'&&currentUser?.role==='pitcher'&&<CreatePitch onSubmit={createPitch} onCancel={()=>setTab('explore')}/>} 
      {tab==='mine'&&currentUser?.role==='pitcher'&&<MyPitches pitches={pitches.filter(p=>p.pitcherId===currentUser.id)} investments={investments} onSelect={setSelected} onStatus={updateStatus} onNew={()=>setTab('create')}/>} 
    </main>
    {selected&&<PitchModal p={selected} user={currentUser} onClose={()=>setSelected(null)} onInvest={invest} onAuth={()=>{setSelected(null);setAuth('signin')}}/>}
    {auth&&<Auth mode={auth} onClose={()=>setAuth(null)} onSwitch={setAuth} onSignIn={signIn} onSignUp={signUp}/>} 
    {funds&&<Funds onClose={()=>setFunds(false)} onAdd={addFunds}/>} 
    {toast&&<div className={`fixed bottom-6 right-6 z-50 px-5 py-3 rounded-xl shadow-2xl text-sm font-bold ${toast.type==='error'?'bg-rose-600':'bg-emerald-600'} text-white`}>{toast.message}</div>}
    <footer className="border-t border-slate-800 py-8 text-center text-xs text-slate-500">© 2026 InnoFund — Connecting Innovators & Angel Backers</footer>
  </div>;
}

function PitchCard({p,onClick}){const pct=Math.min(100,Math.round(p.raisedAmount/p.targetAmount*100));return <button onClick={onClick} className="glass-card rounded-3xl overflow-hidden text-left hover:-translate-y-1 transition-transform"><img src={p.imageUrl} className="w-full h-48 object-cover" alt="pitch"/><div className="p-5"><span className="text-[10px] font-bold uppercase tracking-widest text-emerald-400">{p.category}</span><h2 className="text-lg font-black mt-1">{p.title}</h2><p className="text-xs text-slate-400 mt-2 line-clamp-2">{p.tagline}</p><div className="mt-5"><div className="flex justify-between text-xs"><span className="text-slate-400">{formatINR(p.raisedAmount)} raised</span><b className="text-emerald-400">{pct}%</b></div><div className="h-2 bg-slate-800 rounded-full mt-2 overflow-hidden"><div className="h-full bg-gradient-to-r from-emerald-500 to-teal-400" style={{width:`${pct}%`}}/></div><div className="flex justify-between mt-2 text-[10px] text-slate-500"><span>Goal {formatINR(p.targetAmount)}</span><span>{p.expectedInvestors} slots</span></div></div></div></button>}

function PitchModal({p,user,onClose,onInvest,onAuth}){const [slots,setSlots]=useState(1);return <Overlay><div className="glass-card max-w-3xl w-full max-h-[90vh] overflow-y-auto rounded-3xl p-6"><button onClick={onClose} className="float-right text-slate-400"><i className="fa-solid fa-xmark text-xl"/></button><img src={p.imageUrl} className="w-full h-56 object-cover rounded-2xl" alt="pitch"/><span className="block text-xs font-bold text-emerald-400 uppercase mt-5">{p.category}</span><h2 className="text-3xl font-black mt-1">{p.title}</h2><p className="text-slate-400 mt-2">{p.tagline}</p><p className="text-sm text-slate-300 whitespace-pre-line mt-5">{p.description}</p><div className="grid md:grid-cols-2 gap-4 mt-5"><Info t="Market Opportunity" v={p.marketOpportunity}/><Info t="Milestones" v={p.milestones}/></div><div className="mt-6 p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex justify-between"><b>₹{formatINR(p.minInvestmentPerSlot).replace('₹','')} / slot</b><span className="text-emerald-400 font-bold">{formatINR(p.raisedAmount)} raised</span></div><div className="flex gap-3 mt-4"><input type="number" min="1" max={p.expectedInvestors} value={slots} onChange={e=>setSlots(Math.max(1,Number(e.target.value)))} className="w-24 px-3 rounded-xl bg-slate-950 border border-slate-700"/><button onClick={()=>user?onInvest(p,slots):onAuth()} className="flex-1 py-3 rounded-xl bg-emerald-500 text-slate-950 font-black">Invest {formatINR(p.minInvestmentPerSlot*slots)}</button></div></div></div></Overlay>}
function Info({t,v}){return <div className="p-4 rounded-2xl bg-slate-900/70 border border-slate-800"><b className="text-xs text-slate-400 uppercase">{t}</b><p className="text-sm mt-2 text-slate-200">{v||'Not provided'}</p></div>}
function Overlay({children}){return <div className="fixed inset-0 z-40 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4">{children}</div>}

function Auth({mode,onClose,onSwitch,onSignIn,onSignUp}){const [form,setForm]=useState({name:'',email:'',password:'',role:'investor',company:'',initialWallet:1000000});const submit=e=>{e.preventDefault();mode==='signin'?onSignIn(form.email,form.password):onSignUp(form)};return <Overlay><form onSubmit={submit} className="glass-card w-full max-w-md rounded-3xl p-7"><button type="button" onClick={onClose} className="float-right text-slate-400"><i className="fa-solid fa-xmark"/></button><h2 className="text-2xl font-black">{mode==='signin'?'Welcome back':'Join InnoFund'}</h2><p className="text-xs text-slate-500 mt-1">{mode==='signin'?'Sign in to continue.':'Create a pitcher or investor account.'}</p>{mode==='signup'&&<input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="field"/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="field"/><input required type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="field"/>{mode==='signup'&&<><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="field"><option value="investor">Investor</option><option value="pitcher">Pitcher</option></select><input placeholder="Company" value={form.company} onChange={e=>setForm({...form,company:e.target.value})} className="field"/></>}<button className="w-full py-3 rounded-xl bg-emerald-500 text-slate-950 font-black mt-4">{mode==='signin'?'Sign In':'Create Account'}</button><button type="button" onClick={()=>onSwitch(mode==='signin'?'signup':'signin')} className="w-full text-xs text-slate-400 mt-4">{mode==='signin'?"Don't have an account? Sign up":"Already have an account? Sign in"}</button>{mode==='signin'&&<p className="text-[10px] text-slate-600 mt-5">Demo: vikram@singhaniavc.com / password123</p>}</form></Overlay>}
function Funds({onClose,onAdd}){const [n,setN]=useState(100000);return <Overlay><div className="glass-card w-full max-w-sm rounded-3xl p-7"><button onClick={onClose} className="float-right"><i className="fa-solid fa-xmark"/></button><h2 className="text-xl font-black">Add Investment Capital</h2><input type="number" min="1" value={n} onChange={e=>setN(e.target.value)} className="field"/><button onClick={()=>onAdd(n)} className="w-full py-3 bg-emerald-500 text-slate-950 font-black rounded-xl mt-4">Deposit {formatINR(n)}</button></div></Overlay>}

function Dashboard({currentUser,pitches,investments,onSelect,onFunds,onAuth}){if(!currentUser)return <div className="text-center py-24"><h2 className="text-3xl font-black">Your dashboard awaits</h2><button onClick={onAuth} className="mt-5 px-6 py-3 bg-emerald-500 text-slate-950 font-bold rounded-xl">Sign In</button></div>;const mine=investments.filter(i=>i.investorId===currentUser.id);const total=mine.reduce((s,i)=>s+i.amount,0);return <><h1 className="text-3xl font-black">Welcome, {currentUser.name}</h1><div className="grid md:grid-cols-3 gap-5 mt-6"><Stat t="Wallet Balance" v={formatINR(currentUser.walletBalance)}/><Stat t="Total Invested" v={formatINR(total)}/><Stat t={currentUser.role==='investor'?'Investments':'Live Pitches'} v={currentUser.role==='investor'?mine.length:pitches.filter(p=>p.pitcherId===currentUser.id).length}/></div>{currentUser.role==='investor'&&<><button onClick={onFunds} className="mt-5 px-5 py-3 rounded-xl bg-emerald-500 text-slate-950 font-bold">Add Capital</button><h2 className="text-xl font-black mt-10 mb-4">My Investments</h2><div className="space-y-3">{mine.map(i=><div key={i.id} className="glass-card p-4 rounded-2xl flex justify-between"><span>{i.pitchTitle}<small className="block text-slate-500">{i.date} • {i.slotsCount} slot(s)</small></span><b className="text-emerald-400">{formatINR(i.amount)}</b></div>)}</div></>}</>}
function Stat({t,v}){return <div className="glass-card p-6 rounded-2xl"><span className="text-xs text-slate-500">{t}</span><div className="text-2xl font-black mt-2 text-emerald-400">{v}</div></div>}
function About(){return <div className="max-w-3xl"><p className="text-emerald-400 text-xs font-bold uppercase">About InnoFund</p><h1 className="text-4xl font-black mt-2">A marketplace for early ideas.</h1><p className="text-slate-400 mt-5 leading-7">InnoFund connects innovators raising micro-capital with investors who want to discover and back early-stage campaigns through fractional investment slots.</p><div className="glass-card rounded-2xl p-6 mt-7"><h2 className="font-black">Demo platform notice</h2><p className="text-sm text-slate-400 mt-2">This frontend stores demo accounts, pitches, and investments in browser localStorage. It is not a regulated investment platform and does not process real money.</p></div></div>}
function CreatePitch({onSubmit,onCancel}){const [f,setF]=useState({title:'',tagline:'',category:'AI Tech',customCategory:'',targetAmount:1000000,expectedInvestors:10,imageUrl:IMAGE_PRESETS[0].url,description:'',marketOpportunity:'',milestones:'',demoUrl:''});const s=(k,v)=>setF({...f,[k]:v});return <form onSubmit={e=>{e.preventDefault();onSubmit(f)}} className="max-w-3xl glass-card rounded-3xl p-7"><h1 className="text-3xl font-black">Post Your Idea</h1>{[['title','Pitch title'],['tagline','One-line tagline'],['targetAmount','Target amount'],['expectedInvestors','Expected investors'],['marketOpportunity','Market opportunity'],['milestones','Milestones'],['demoUrl','Demo URL']].map(([k,p])=><input key={k} required={k==='title'||k==='tagline'} type={['targetAmount','expectedInvestors'].includes(k)?'number':'text'} value={f[k]} onChange={e=>s(k,e.target.value)} placeholder={p} className="field"/>)}<select value={f.category} onChange={e=>s('category',e.target.value)} className="field">{['AI Tech','Clean Energy','Healthcare','Food Tech','EdTech','Fintech','Other'].map(x=><option key={x}>{x}</option>)}</select>{f.category==='Other'&&<input value={f.customCategory} onChange={e=>s('customCategory',e.target.value)} placeholder="Custom category" className="field"/>}<textarea required value={f.description} onChange={e=>s('description',e.target.value)} placeholder="Describe your idea, problem and solution" className="field h-40"/><div className="flex gap-3 mt-5"><button type="button" onClick={onCancel} className="px-5 py-3 rounded-xl bg-slate-800 font-bold">Cancel</button><button className="flex-1 py-3 rounded-xl bg-emerald-500 text-slate-950 font-black">Publish Pitch</button></div></form>}
function MyPitches({pitches,investments,onSelect,onStatus,onNew}){return <div><div className="flex justify-between items-center"><h1 className="text-3xl font-black">My Pitch Campaigns</h1><button onClick={onNew} className="px-4 py-2 rounded-xl bg-emerald-500 text-slate-950 text-xs font-bold">+ Post Idea</button></div><div className="grid md:grid-cols-2 gap-5 mt-6">{pitches.map(p=><div key={p.id} className="glass-card p-5 rounded-2xl"><span className="text-xs text-emerald-400">{p.category}</span><h2 className="font-black mt-1">{p.title}</h2><div className="flex justify-between text-xs mt-5"><span>{formatINR(p.raisedAmount)} raised</span><select value={p.status} onChange={e=>onStatus(p.id,e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-2"><option>Active</option><option>Funded</option><option>Closed</option></select></div><button onClick={()=>onSelect(p)} className="w-full mt-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs font-bold">Inspect</button></div>)}</div></div>}
